services:
  - type: web
    name: netflix-recommender-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5000
    buildFilter:
      paths:
        - app.py
        - requirements.txt
        - runtime.txt
        - netflix_movies.csv # ✅ include CSV
